In [176]:
# y = 0.1x^3 + 0.5x^2 + 0x + 0.1
import numpy as np
from random import seed
seed(1)

In [177]:
# function declaration
def J(h_, y_, m):
    return sum((sum(h_.T).T - y_) ** 2 / 2 / m)

def learn(X_, h_, y_):
    return np.dot(X_.T, (h_ - y_)) / X_.shape[0]

def h_x(X_, w_):
    return np.dot(X_, w_)

def f(X_):
    return .1 * X_ ** 3 + .5 * X_ ** 2 + 0 + .1

In [178]:
# data
X = np.array(list(range(0, 4)))
y = f(X).T
X = np.array([np.ones(X.size), X, X ** 2, X ** 3, X ** 4]).T
X[0], y[0]

(array([1., 0., 0., 0., 0.]), 0.1)

In [179]:
# w = np.random.random(X.shape[1]) * 2 - 1
w = np.array([0.31551563, 0.68650093, 0.83462567, 0.01828828, 0.75014431]) * 2 - 1
h = h_x(X, w)
cost = J(h, y, X.shape[0])

[-0.36896874  0.37300186  0.66925134 -0.96342344  0.50028862]
[  -3.73814271  -10.2183541   -31.12410635  -96.13715095 -284.36327761]
[  7959.14656337  22294.79640983  63935.53920675 186120.23134681
 547210.63984846]
[-1.53389566e+07 -4.29605683e+07 -1.23194584e+08 -3.58623058e+08
 -1.05436132e+09]
[2.95550819e+10 8.27763574e+10 2.37371118e+11 6.90994271e+11
 2.03154147e+12]
[-5.69466780e+13 -1.59493335e+14 -4.57366239e+14 -1.33140651e+15
 -3.91437042e+15]
[1.09724756e+17 3.07311468e+17 8.81252437e+17 2.56535164e+18
 7.54220181e+18]
[-2.11417460e+20 -5.92127178e+20 -1.69799559e+21 -4.94291487e+21
 -1.45323007e+22]
[4.07358777e+23 1.14090957e+24 3.27169482e+24 9.52399938e+24
 2.80008106e+25]
[-7.84898151e+26 -2.19830248e+27 -6.30389564e+27 -1.83508247e+28
 -5.39519110e+28]
[1.51234033e+30 4.23568523e+30 1.21463347e+31 3.53583357e+31
 1.03954444e+32]


In [180]:
a = 1
d = learn(X, h, y)
print(w)
for i in range(10):
    h = h_x(X, w)
    d = a * learn(X, h, y)
    cost = J(h, y, X.shape[0])
    w -= d
    print(w)

[-0.36896874  0.37300186  0.66925134 -0.96342344  0.50028862]
[  -3.73814271  -10.2183541   -31.12410635  -96.13715095 -284.36327761]
[  7959.14656337  22294.79640983  63935.53920675 186120.23134681
 547210.63984846]
[-1.53389566e+07 -4.29605683e+07 -1.23194584e+08 -3.58623058e+08
 -1.05436132e+09]
[2.95550819e+10 8.27763574e+10 2.37371118e+11 6.90994271e+11
 2.03154147e+12]
[-5.69466780e+13 -1.59493335e+14 -4.57366239e+14 -1.33140651e+15
 -3.91437042e+15]
[1.09724756e+17 3.07311468e+17 8.81252437e+17 2.56535164e+18
 7.54220181e+18]
[-2.11417460e+20 -5.92127178e+20 -1.69799559e+21 -4.94291487e+21
 -1.45323007e+22]
[4.07358777e+23 1.14090957e+24 3.27169482e+24 9.52399938e+24
 2.80008106e+25]
[-7.84898151e+26 -2.19830248e+27 -6.30389564e+27 -1.83508247e+28
 -5.39519110e+28]
[1.51234033e+30 4.23568523e+30 1.21463347e+31 3.53583357e+31
 1.03954444e+32]


array([0., 0., 0.])